#!/bin/bash

./gradlew lockCommitToMainHook

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch. Refer to the contributing guidelines."
  exit 1
fi